### ISSUE TITLE
Error in mesh edit mode.

### ISSUE THREAD

**Issue by Jago1996** [ndee85/coa_tools#110]
> Traceback (most recent call last):
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 1221, in modal
>     bpy.context.scene.cursor_location = self.limit_cursor_by_bounds(context,scene.cursor_location)
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 820, in limit_cursor_by_bounds
>     bounds.append(obj.matrix_world.inverted() * point)
> ValueError: Matrix.invert(ed): matrix does not have an inverse
> Traceback (most recent call last):
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 1186, in modal
>     return self.exit_edit_mode(context,event)
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 1367, in exit_edit_mode
>     bpy.types.SpaceView3D.draw_handler_remove(self.draw_handler, "WINDOW")
> ValueError: callback_remove(handle): NULL handle given, invalid or already removed
> Traceback (most recent call last):
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 1186, in modal
>     return self.exit_edit_mode(context,event)
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 1367, in exit_edit_mode
>     bpy.types.SpaceView3D.draw_handler_remove(self.draw_handler, "WINDOW")
> ValueError: callback_remove(handle): NULL handle given, invalid or already removed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 1363, in modal
>     self.exit_edit_mode(context,event)
>   File "AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\operators\edit_mesh.py", line 1367, in exit_edit_mode
>     bpy.types.SpaceView3D.draw_handler_remove(self.draw_handler, "WINDOW")
> ValueError: callback_remove(handle): NULL handle given, invalid or already removed
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

This happens when I either start cutting with the knife tool or when I hover over the 3d view while editing a mesh. This doesn't happen everytime if I figure out the cause exactly I'll update this.

**Comment by RobertBalogh** [comment]
I have a same issue. I tried apply this add on from file and by pithon. Neither has succes with it. I hope someone can help me with it. Many thanks for your hard work guys.

**Comment by ndee85** [comment]
Could you provide a file which I can look into?
