### ISSUE TITLE
Blender 2.9

### ISSUE THREAD

**Issue by Alekzs89** [ndee85/coa_tools#172]
Upgrade to 2.8x is required.

Is there a solution to this or i need to downgrade?

Thank you.

**Comment by davord45** [comment]
Have you tried blender28 branch?

**Comment by kreezii** [comment]
[#176](https://github.com/ndee85/coa_tools/pull/176)
If you are going to export to DragonBones I made a pull request to work with Blender 2.9. Meanwhile there is a [fork](https://github.com/kreezii/coa_tools/tree/blender29) in my repositories you can use.

**Comment by davord45** [comment]
Woah thanks for adding support for 2.9,i had some trouble trying to fix it.May i add those fixes to my fork?
I added some new features to DragonBones exporter,like Z depth,events and curve export.

**Comment by notsosimpleton** [comment]
Just curious if anyone has figured out how to make this work with 2.9? Or are we just waiting for it to be updated?

**Comment by Lertsenem** [comment]
Waiting for the update. Meanwhile I'm using Blender 2.83 LTS.

**Comment by magdesign** [comment]
@kreezii : Thanks for your fork, just tried it on Blender 2.91 on Ubuntu Linux.
Unfortunately after importing a sprite and clicking "Edit Armature" I get following error:
```

  File "/home/magdesign/.config/blender/2.91/scripts/addons/coa_tools/operators/edit_armature.py", line 152, in project_cursor
    ray = bpy.context.scene.ray_cast(bpy.context.view_layer, start, (start+(end-start)*2000)-start )
TypeError: Scene.ray_cast(): error with argument 1, "depsgraph" -  Function.depsgraph expected a Depsgraph type, not ViewLayer
Error: An Error occured, please check the console for more information


```

**Comment by kreezii** [comment]
@magdesign : It seems It breaks on every release... I updated it and trying it with Blender 2.91 seems to work fine now. [Here](https://github.com/kreezii/coa_tools/releases/tag/v2.0.1b) is the new release, please let me know if everything is working well for you too.

**Comment by KolaiUA** [comment]
Thanks for the update for 2.91, man! Everything works! But the negative bone scale does not work. Do you know how to fix it?

**Comment by davord45** [comment]
Thanks @kreezii you are awesome!

**Comment by magdesign** [comment]
@kreezii : thanks for your effort, works here again :-)

**Comment by sirdavid32** [comment]
I'm trying it on 2.92 and I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\coa_tools\operators\edit_mesh.py", line 1265, in execute
    self.edit_object, self.texture_preview_object = self.prepare_edit_object(context)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\coa_tools\operators\edit_mesh.py", line 1193, in prepare_edit_object
    v_group = original_object.vertex_groups["coa_base_sprite"]
KeyError: 'bpy_prop_collection[key]: key "coa_base_sprite" not found'

location: <unknown location>:-1

**Comment by sirdavid32** [comment]
I import the sprite through the COA Tools N side bar, and when I try to edit the mesh I get this error (2.91, 2.92)
![101](https://user-images.githubusercontent.com/11066585/101336037-f5a50c00-3847-11eb-871a-da0ec930b89a.jpg)

**Comment by sirdavid32** [comment]
I'm getting this error when I try to edit the mesh (sprite) in 2.92 and 2.91:
Tool 'coa_tools.draw_polygon' not found for space 'VIEW_3D'.
![101](https://user-images.githubusercontent.com/11066585/101339755-d492ea00-384c-11eb-9b83-79bb5720d9a7.jpg)

**Comment by davord45** [comment]
@sirdavid32 Did you try @kreezii pull request for Blender 2.9?

**Comment by sirdavid32** [comment]
Thank you for your reply and the heads up. I downloaded it and installed it on 2.92. I get this error when I import a sprite: Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\coa_toolsaddon\operators\import_sprites.py", line 429, in execute
    bpy.ops.coa_tools.reimport_sprite(filepath=filepath,name=i.name, reposition=False)
  File "E:\Program Files\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\coa_toolsaddon\operators\import_sprites.py", line 541, in execute
    self.move_verts(obj, ratio_x, ratio_y)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\coa_toolsaddon\operators\import_sprites.py", line 468, in move_verts
    bpy.ops.object.mode_set(mode="EDIT")
  File "E:\Program Files\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: E:\Program Files\Blender 2.92\2.92\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1


In Blender 2.91 it works, but when I finish editing with the Edit Mesh tools, I get this message still: 
Tool 'coa_tools.draw_polygon' not found for space 'VIEW_3D'.

**Comment by jwhang627** [comment]
Whenever I upgrade to @kreezii's update, I get this error.

![Screenshot 2021-06-18 221351](https://user-images.githubusercontent.com/14305330/122620460-105f0580-d061-11eb-829f-7df33f7b0317.png)

**Comment by ndee85** [comment]
Hey guys,
Could someone post a blend file that does not work. Tested yesterday with 2.93.3 and it worked fine for me. Will try to fix that issue.

**Comment by magdesign** [comment]
here the blender file:
https://mega.nz/file/Rjp21JoA#SDKji8SP7nJ2hjjPZrdAemKSkeO__EP_30JRngwIrsI


Ubuntu 18.04 LTS
Blender 2.93.3
CoaTools coa_tools-2.0.0 from [here](https://github.com/ndee85/coa_tools/releases)

What I did:

1.) Installed Coa-tools as described in the readme.md
2.) COA Tools Panel: 2D View
3.) COA Tools Panel: Create new Sprite Object
4.) COA Tools Panel: Re / Import Sprites
5.) Select my .png to import
6.) COA Tools Panel: Edit Armature
7.) Following error occurs:

![edit_sprite](https://user-images.githubusercontent.com/5273166/129900781-9213987f-4d65-4262-9d43-a0dc6e4b0749.png)
