### ISSUE TITLE
edit mesh bug

### ISSUE THREAD

**Issue by darko-art** [ndee85/coa_tools#179]
hey everyone, i have this problem in coa tools edit mesh 

Python: Traceback (most recent call last):
  File "C:\Users\Darko\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\coa_tools\operators\edit_mesh.py", line 1268, in execute
    self.edit_object, self.texture_preview_object = self.prepare_edit_object(context)
  File "C:\Users\Darko\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\coa_tools\operators\edit_mesh.py", line 1196, in prepare_edit_object
    v_group = original_object.vertex_groups["coa_base_sprite"]
KeyError: 'bpy_prop_collection[key]: key "coa_base_sprite" not found'

location: <unknown location>:-1

**Comment by legendA1tair** [comment]
i have the same issue
