### ISSUE TITLE
Can't install in blender 2.92

### ISSUE THREAD

**Issue by legendA1tair** [ndee85/coa_tools#182]
this error comes up 
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\coa_tools\__init__.py", line 264, in register
    addon_updater_ops.register(bl_info)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\coa_tools\addon_updater_ops.py", line 1099, in register
    showReloadPopup()
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\coa_tools\addon_updater_ops.py", line 677, in showReloadPopup
    saved_state = updater.json
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\coa_tools\addon_updater.py", line 275, in json
    self.set_updater_json()
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\coa_tools\addon_updater.py", line 1255, in set_updater_json
    self.save_updater_json()
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\coa_tools\addon_updater.py", line 1273, in save_updater_json
    outf = open(jpath,'w')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\Blender 2.92\\2.92\\scripts\\addons\\coa_tools\\coa_tools_updater\\updater_status.json'

also i tried COA 2.0, 2.1 , and COA blender 28, i am confused on whats going on 
HELP!

**Comment by legendA1tair** [comment]
Okay so i fixed some of the issues on the callback error because i ran blender as admin, now its showing this: 

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\coa_tools\__init__.py", line 295, in unregister
    bpy.utils.unregister_tool(edit_mesh.COATOOLS_TO_DrawPolygon)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\utils\__init__.py", line 909, in unregister_tool
    tool_def = tool_cls._bl_tool
AttributeError: type object 'COATOOLS_TO_DrawPolygon' has no attribute '_bl_tool'

**Comment by legendA1tair** [comment]
Fixed it: Install coa then close/open Blender
