### ISSUE TITLE
slot Object not working at render.

### ISSUE THREAD

**Issue by ahrimanes** [ndee85/coa_tools#192]
ok I have this working and Im doing some stuff.. but when it comes to slot index to shift betwiin sprites I get an error every time i try to set a keyframe, if I press "i" it works but it only works on play time if I render I only see the index im on when render animation button was pressed..

the error is:
Traceback (most recent call last):
  File "C:\Users\ahrim\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\coa_tools\operators\animation_handling.py", line 132, in invoke
    self.execute(context)
  File "C:\Users\ahrim\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\coa_tools\operators\animation_handling.py", line 162, in execute
    self.create_keyframe(context,event,self.prop_name)
  File "C:\Users\ahrim\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\coa_tools\operators\animation_handling.py", line 77, in create_keyframe
    sprite.keyframe_insert(data_path)
TypeError: bpy_struct.keyframe_insert() property "coa_slot_index" not found

i did as you said before on other issues,, select all sprites i want to make them slot and press the merge..

it seems my objects have missin properties "coa_slot_index"?? how can i solve it?

**Comment by ahrimanes** [comment]
i have just double cheked and this issue occurs with the sample file aswell..

**Comment by SallyElsa** [comment]
![Screenshot 2021-12-23 153604](https://user-images.githubusercontent.com/45052953/147299868-2f6ab5b6-149f-4665-837d-11bbc8ec082d.png)

I'm having the same issue, Blender 2.83 and COA tools 2.0.1  
I'm not the most tech savy, so I don't really understand how to bypass this error

**Comment by ahrimanes** [comment]
for what i have seen there is no custom properties defined by Api on the objects..

**Comment by ahrimanes** [comment]
ok i have searched the string "coa_solt_index" on the 2.0.0 src traing to find the fucntion wich create that property and i just find 2 hits on ui.py   while i have 34 hits on 1.0.4.. sooo i guess is an un suporte feature sicen the src is not refering to it out side the ui.py wich creates the ui item.
