### ISSUE TITLE
Error activating addon on blender 2.79 64bit in windows 10

### ISSUE THREAD

**Issue by ceciox** [ndee85/coa_tools#81]
Installed following instructions (unzipping package and zipping subdir coa_tools).
I can't enable addon: 

coa_tools updater verbose is enabled
Exception in module register(): 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\coa_tools\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\__init__.py", line 136, in register
    addon_updater_ops.register(bl_info)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\addon_updater_ops.py", line 1099, in register
    showReloadPopup()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\addon_updater_ops.py", line 677, in showReloadPopup
    saved_state = updater.json
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\addon_updater.py", line 275, in json
    self.set_updater_json()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\coa_tools\addon_updater.py", line 1237, in set_updater_json
    os.makedirs(self._updater_path)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Accesso negato: 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\coa_tools\\coa_tools_updater'

**Comment by ndee85** [comment]
Hi ceciox,
this seems to be a permission problem with the new updater module. Try running blender as administrator and then enabling the addon. Afterwards it should work ok, even not as admin.
I will preinclude the coa_tools_updater folder for future releases.

It seems to be a known issue with the updater module:
johnroper100/CrowdMaster#57

**Comment by ndee85** [comment]
ok. I added this folder. If you get latest master version, everything should work fine. At least I hope so :)

**Comment by TheDuckCow** [comment]
It's a permission issue with being able to create folders. Yeah I find this issue strange, not sure why some (and only some... even without admin..) windows users have blender instances which don't have the permission to add folders to the python/addons folder, I suppose it depends on where it is installed. 

I think I'll make this note more obvious in the documentation.

**Comment by ceciox** [comment]
Thank you, I'm in trouble so I can't try the plugin. I'll try it as soon as
possible.

Max

Il 10 feb 2018 6:18 PM, "Patrick W. Crawford" <notifications@github.com> ha
scritto:

It's a permission issue with being able to create folders. Yeah I find this
issue strange, not sure why some (and only some... even without admin..)
windows users have blender instances which don't have the permission to add
folders to the python/addons folder, I suppose it depends on where it is
installed.

I think I'll make this note more obvious in the documentation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ndee85/coa_tools/issues/81#issuecomment-364673238>, or mute
the thread
